name: Security and CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

  trufflehog:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Clone repository
      run: git clone https://github.com/jai3747/31-aug-task.git

    - name: Determine scan range
      id: scan_range
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          BASE="${{ github.event.before }}"
          HEAD="${{ github.event.after }}"
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
          BASE="${{ github.event.pull_request.base.sha }}"
          HEAD="${{ github.event.pull_request.head.sha }}"
        else
          BASE=$(git rev-parse HEAD~10)
          HEAD="HEAD"
        fi
        echo "base=${BASE}" >> $GITHUB_OUTPUT
        echo "head=${HEAD}" >> $GITHUB_OUTPUT

    - name: Run TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./31-aug-task
        base: ${{ steps.scan_range.outputs.base }}
        head: ${{ steps.scan_range.outputs.head }}
        extra_args: --debug --only-verified --json

    - name: Print TruffleHog Output
      if: always()
      run: |
        echo "TruffleHog Scan Results:"
        if [ -f 31-aug-task/trufflehog-results.json ]; then
          cat 31-aug-task/trufflehog-results.json
        else
          echo "No results file found. TruffleHog did not detect any issues."
        fi
        echo "End of TruffleHog Scan Results"

    - name: Upload TruffleHog results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: trufflehog-results
        path: 31-aug-task/trufflehog-results.json
        if-no-files-found: ignore

  sca_snyk:
    runs-on: ubuntu-latest
    needs: trufflehog
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install Snyk
      run: npm install -g snyk

    - name: Authenticate Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    - name: Run Snyk to check for vulnerabilities
      run: snyk test --json > snyk_report.json || true

    - name: Upload Snyk report
      uses: actions/upload-artifact@v2
      with:
        name: snyk-report
        path: snyk_report.json

  semgrep:
    runs-on: ubuntu-latest
    needs: sca_snyk
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep --config auto --json > semgrep_report.json

    - name: Upload Semgrep report
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-report
        path: semgrep_report.json

    - name: Convert Semgrep report to SARIF
      run: semgrep --config auto --sarif > semgrep.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif

  build_and_scan:
    runs-on: ubuntu-latest
    needs: semgrep
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --file Dockerfile --tag my-node-app --load .

    - name: Check if Docker image was built
      run: |
        if ! docker images | grep my-node-app; then
          echo "Docker image 'my-node-app' not found. Build failed."
          exit 1
        fi

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@v0.10.0
      with:
        image-ref: my-node-app
        format: 'table'
        output: 'trivy-report.txt'
      
    - name: Check Trivy scan results
      run: |
        if grep -q "CRITICAL" trivy-report.txt; then
          echo "Critical vulnerabilities found in Docker image!"
          exit 1
        else
          echo "No critical vulnerabilities found in Docker image."
        fi

    - name: Upload Trivy scan report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy-report.txt
